Update ProtonVPN instructions to include recent addition of Wireguard
qdm12/gluetun-wiki pull request #90
Opened 2024-08-15 16:45 UTC by MaVdbussche

Update ProtonVPN instructions to include recent addition of Wireguard support in https://github.com/qdm12/gluetun/pull/2390

References to the custom provider have been removed as it is not necesary anymore.

This PR is mostly based on the comment of @TheRealBix (https://github.com/qdm12/gluetun/pull/2390#issuecomment-2266670716) in the upstream PR.

I tested those instructions in my environment and can confirm they are complete.

2024-09-14 10:24 UTC, qdm12 commented on setup/options/port-forwarding.md
> +| `VPN_PORT_FORWARDING_PROVIDER` | Current provider in use | `private internet access` | Choose the custom port forwarding code to use. This is useful when using the custom provider with Wireguard. F
Note to myself: add `v4` comment to remove protonvpn as an option in the code

2024-09-14 10:24 UTC, qdm12 commented on setup/providers/protonvpn.md
>  - `VPN_PORT_FORWARDING=on`
```suggestion
For both openvpn and wireguard, you need to set `VPN_PORT_FORWARDING=on`.
```

2024-09-14 12:49 UTC, MaVdbussche commented
@qdm12 I integrated your remarks and fixed the linting errors.
Note I didn't test this provider with OpenVPN so I trust your review blindly ;)

2025-01-25 07:13 UTC, qdm12 requested changes
sorry for the massive delay, and thanks for your patience!

2025-01-25 07:13 UTC, qdm12 commented on setup/wireguard.md
> +- [ProtonVPN](providers/protonvpn.md)
Can you insert this alphabetically in the list? Thanks! 🙏

2025-01-25 07:13 UTC, qdm12 commented on setup/providers/protonvpn.md
> -- Add `+pmp` to your OpenVPN username (thanks to [@mortimr](https://github.com/qdm12/gluetun/issues/1760#issuecomment-1669518288))
That requirement is still needed for Openvpn users, please restore it

2025-01-26 17:03 UTC, qdm12 approved these changes

2025-01-26 17:03 UTC, merged